/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import { useState } from 'react'
import { Inter } from 'next/font/google'
import classes from '@/styles/Home.module.css'
import Header from '@/components/Header'
import { Divider, Icon, Badge } from '@mui/material'
import clsx from 'clsx'
const inter = Inter({ subsets: ['latin'] })
import MoreVertIcon from '@mui/icons-material/MoreVert';
export default function Home() {
  const [selectedTab, setSelectedTab] = useState('Basic Info')
  return (
    <>
      <Head>
        <title>WeWork</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={`${classes.main} ${inter.className}`}>
        <Header />
        <Divider variant='middle' flexItem />
        <div className={classes.mainContent}>
          <div className={clsx(classes.pageHeadingContainer, 'boldText')}>
            <span className={classes.heading}>WeWork + SalesForce</span>
            <div className={classes.publishButton}>
              Publish/Share
            </div>
          </div>
          < div className={classes.bannerContainer}>
            <img src='/banner.png' alt="banner" className={classes.banner} />
            <img className={classes.secondaryBanner} src='/secondary-banner.png' alt="secondary banner" />
          </div>
          <div className={classes.scopeContainer}>
            <span>Project Scope Recap</span>
            <div className={classes.actionPlanContainer}>
              <div className={classes.actionPlanCTA}>
                <span>Mutual Action Plan</span>
                <span className={classes.actionPlanCTABold}>3%</span>
              </div>
              <div className={classes.actionPlanProgress}>
                {Array(17).fill(0).map((element, index) => {
                  return (
                    <div className={classes.progressBarItem} key={index}></div>
                  )
                })}
              </div>
            </div>
          </div>
          <div className={classes.actionTabsContainer}>
            <div className={classes.tabsGroup}>
              {['Basic Info', 'Files', 'Mutual Action Plan', 'Contact'].map((element, index) => {
                return (
                  <div className={clsx(classes.tab, {
                    [classes.tabSelected]: selectedTab.toLowerCase() === element.toLowerCase()
                  })} key={element}>{element}</div>)
              })}
            </div>
            
            <div className={classes.tabsGroup}>
              <div className={classes.tab} style={{
              }}>
                Internal Actions
              </div>
            </div>

          </div>
          <div className={classes.companyOverview}>
            <div className={classes.navBarVertical}>
              <div className={classes.navBarHeading}>Overview</div>
              <Divider variant='middle' flexItem />
              {['Welcome', 'Product Capabilities', 'Customer Success Stories', 'File Sharing', 'Our Deck'].map((element, index, arr) => {
                return (
                  <>
                    <div className={classes.navBarItem} key={element}>{element}</div>
                    {index + 1 !== arr.length && (<Divider variant='middle' flexItem />)}
                  </>
                )
              })}
            </div>
            <div className={classes.companyContent}>
              <div className={classes.companyContentHeader}>
                <span>Company Profile</span>
                <div className={classes.headerTools}>
                  <Icon sx={{ marginTop: -1 }}>
                    <img src="/arrow_down.png" alt="icon" style={{
                      height: 16, width: 10.5,
                    }} />
                  </Icon>
                  <Divider variant='middle' orientation='vertical' flexItem />
                  <Icon>
                    <img src="/eye-off.png" alt="icon" />
                  </Icon>
                  <Divider variant='middle' orientation='vertical' flexItem />
                  <Icon>
                    <img src="/delete.png" alt="icon" />
                  </Icon>
                </div>
                <div className={classes.mobileHeaderTools}>
                  <MoreVertIcon />
                </div>
              </div>
              <div className={classes.companyContentMain}>
                <div className={clsx(classes.tools, classes.headerTools)}>
                  <div style={{ display: 'flex', gap: 30 }}>
                    <div className={classes.pageNumber}>
                      <img src="/pdf.png" alt="icon" style={{ height: 24, width: 22 }} />
                      1/15
                    </div>
                    <img src="/arrow_download.png" alt="icon" style={{ height: 20, width: 14.5, }} />
                  </div>
                  <Divider variant='middle' orientation='vertical' flexItem />
                  <img src="/zoom_out.png" alt="icon" />
                  <Divider variant='middle' orientation='vertical' flexItem />
                  <img src="/zoom_in.png" alt="icon" />
                  <Divider variant='middle' orientation='vertical' flexItem />
                  <img src="/open.png" alt="icon" />
                </div>
                <div className={classes.companyTagline}>
                  <img src='/wework-logo.png' alt='logo' />
                  <span>{"For all the ways you work, we're here"}</span>
                </div>
              </div>
              <div className={classes.contentShareTools}>
                <Badge badgeContent={5} color='success'>
                  <img src="/chat.png" alt="icon" style={{ height: 25, width: 25 }} />
                </Badge>
                <hr />
                <img src="/share.png" alt="icon" />
              </div>
            </div>
          </div>
        </div>

      </main>
    </>
  )
}
