/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import classes from '@/styles/Home.module.css'
import Header from '@/components/Header'
import { Divider } from '@mui/material'
import clsx from 'clsx'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>DealIntent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={`${classes.main} ${inter.className}`}>
        <Header />
        <Divider variant='middle' flexItem />
        <div className={classes.mainContent}>
          <div className={clsx(classes.pageHeadingContainer, 'boldText')}>
            <span className={classes.heading}>WeWork + SalesForce</span>
            <div className={classes.publishButton}>
              Publish/Share
            </div>
          </div>
          < div className={classes.bannerContainer}>
            <img src='/banner.png' alt="banner" className={classes.banner} />
            <img className={classes.secondaryBanner} src='/secondary-banner.png' alt="secondary banner" />
          </div>
          <div className={classes.scopeContainer}>
            <span>Project Scope Recap</span>
            <div className={classes.actionPlanContainer}>
              <div className={classes.actionPlanCTA}>
                <span>Mutual Action Plan</span>
                <span className={classes.actionPlanCTABold}>3%</span>
              </div>
              <div className={classes.actionPlanProgress}>
                {Array(17).fill(0).map((element, index) => {
                  return (
                    <div className={classes.progressBarItem} key={index}></div>
                  )
                })}
              </div>
            </div>
          </div>
          <div className={classes.actionTabsContainer}>
            <div className={classes.tabsGroup}>
              {['Basic Info', 'Files', 'Mutual Action Plan', 'Contact'].map((element, index) => {
                return (
                  <div className={classes.tab} key={element}>{element}</div>)
              })}
            </div>
            <div className={classes.tabGroup}>
              <div className={classes.tab} style={{
                background: 'none',
                color: '#657372'
              }}>
                Internal Actions
              </div>
            </div>

          </div>
        </div>
        <div className={classes.companyOverview}>
          <div className={classes.navBarVertical}>
            <div className={classes.navBarHeading}></div>
            {['Welcome', 'Product Capabilities', 'Customer Success Stories', 'File Sharing', 'Our Deck'].map((element) => {
              return (
                <div className={classes.navBarItem} key={element}>{element}</div>
              )
            })}
          </div>
        </div>
      </main>
    </>
  )
}
